app:
  name: kalpa-simple-git
  baseModule: simple-git
  baseModuleSlug: simpleGit
  version: 0.0.0
  description: "Kalpa module for git"
  author: Vinay Patil
  maintainer: vinay.hpatil@gmail.com
  git: patilvinay/kalpa-simple-git
  genpath: ../kalpa-simple-git
